### ISSUE TITLE
Замечания по Mini Dictionary

### ISSUE THREAD

**Issue by alexey-malov** [DavidArutiunian/OOP#1]
https://github.com/DavidArutiunian/OOP/blob/c1e06a62fcb14035484fb57abd5cadf26f941d69/src/main/java/labs/lab2/mini_dictionary/Dictionary.java#L9-L22

- [x] Интерфейс слишком широкий. Многие клиенты используют лишь его часть. Читайте про Interface Segregation Principle (Принцип разделения интерфейса)

- [x] Зачем наружу выставять кишки в виде map?

- [x] Это словарь. Никаких key и value

- [x] Метод clear не используется нигде, кроме тестов. Выпилить.

Читайте принципы SOLID.

**Comment by alexey-malov** [comment]
https://github.com/DavidArutiunian/OOP/blob/c1e06a62fcb14035484fb57abd5cadf26f941d69/src/main/java/labs/lab2/mini_dictionary/Dispatcher.java#L5-L11

- [ ] Сделайте лучше интерфейс EventLoopDelegate с методами:
- onEmptyInput()
- onFinish() (вместо savedict+exit)

**Comment by DavidArutiunian** [comment]
Добавил делегат
```java
public interface EventLoopDelegate {
    void onEmptyInput(final String word);

    void onFinishWord(final String word, final Runnable callback) throws IOException;

    void onInputWord(final String word);
}
```
и состояние EventLoop https://github.com/DavidArutiunian/OOP/blob/master/src/main/java/labs/lab2/mini_dictionary/EventLoopState.java

**Comment by DavidArutiunian** [comment]
Возникла ещё идея упрощения:
В метод `run` аргументом пихать сразу контроллер, а не в `EventLoopState`.
Соотвественно `run` бы и была машиной состояний, выщывающая методы контроллера
Но возможно в этом случае у `run` было бы слишком много обязанностей (взять из инпута, обработать инпут, вызвать контроллер), и можно было бы вернуть диспетчера

**Comment by alexey-malov** [comment]
- [ ] Подразумевалось, что EventLoop определит, по введённой пользователем строке, что именно было введено и вызовет соотв. метод делегата, а не будет просто пихать в делегат одно и то же значение

**Comment by alexey-malov** [comment]
- [ ] InteractionController должен реализоывавть интерфейс, через которые парсер пользовательского ввода будет делегировать ему выполнение операций.

**Comment by alexey-malov** [comment]
- [ ] Упростить тело Main.main()

**Comment by alexey-malov** [comment]
- [ ] FileDictionaryProvider - ничего не провайдит.

**Comment by alexey-malov** [comment]
- [ ] InteractionController.onInputWord - выделить цикл в отдельный метод.

**Comment by alexey-malov** [comment]
- [ ] Словарь при загрузке можно вообще вернуть (новый), а не мутировать переданный снаружи (легко забыть его почистить перед этим).
